import React from "react";

export const GeneralContext = React.createContext({
    test: () => {},
    callTestStrategy: async (testParams:any)=>{},
    callDeployStrategy: async (params: any)=>{},
    checkMetamask: () =>{},
    connectMetamask: async () =>{},
    account: '' as string,
    dateBacktest: '' as string,
    timeFrameBacktest: 0 as number,
    leverageFactor: 0 as number,
    windowSize: 0 as number,
    assetAmount: 0 as number,
    assetBacktest: '' as string,
    getAccounts: async () =>{},
    setBacktestDate: async (date:string) =>{},
    setTimeFrame: async (amount:number) =>{},
    setLeverageFactor: async (amount:number) =>{},
    setWindowSize: async (amount:number) =>{},
    setAssetAmount: async (amount:number) =>{},
    setBacktestAsset: async (asset:string) =>{},
    strategyManagerContract:()=> {},
    approveStrategyContract:async () =>{},
    createStrategy: async (
        creditManagerAddress:any,
        timeframe:any,
        windowSize:any,
        usdcAmount:any,
        usdcAddress:any,
        wethAddress:any,
        uniV2UsdcAdapter:any,
        yearnVault:any,
        leverageFactor:any,
        )=> {}
})